//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceTest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Converter.Tests.ResourceTest", typeof(ResourceTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Mary   had a little  lamb  . 
        ///
        ///
        ///  Peter   called for the wolf   ,  and Aesop came .
        /// Cinderella  likes shoes..
        /// </summary>
        internal static string LongTextInput {
            get {
                return ResourceManager.GetString("LongTextInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,Word 1,Word 2,Word 3,Word 4,Word 5,Word 6,Word 7,Word 8,
        ///Sentence 1, a, had, lamb, little, Mary
        ///Sentence 2, Aesop, and, called, came, for, Peter, the, wolf
        ///Sentence 3, Cinderella, likes, shoes
        ///.
        /// </summary>
        internal static string LongTextOutputCsv {
            get {
                return ResourceManager.GetString("LongTextOutputCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;text&gt;
        ///  &lt;sentence&gt;
        ///    &lt;word&gt;a&lt;/word&gt;
        ///    &lt;word&gt;had&lt;/word&gt;
        ///    &lt;word&gt;lamb&lt;/word&gt;
        ///    &lt;word&gt;little&lt;/word&gt;
        ///    &lt;word&gt;Mary&lt;/word&gt;
        ///  &lt;/sentence&gt;
        ///  &lt;sentence&gt;
        ///    &lt;word&gt;Aesop&lt;/word&gt;
        ///    &lt;word&gt;and&lt;/word&gt;
        ///    &lt;word&gt;called&lt;/word&gt;
        ///    &lt;word&gt;came&lt;/word&gt;
        ///    &lt;word&gt;for&lt;/word&gt;
        ///    &lt;word&gt;Peter&lt;/word&gt;
        ///    &lt;word&gt;the&lt;/word&gt;
        ///    &lt;word&gt;wolf&lt;/word&gt;
        ///  &lt;/sentence&gt;
        ///  &lt;sentence&gt;
        ///    &lt;word&gt;Cinderella&lt;/word&gt;
        ///    &lt;word&gt;likes&lt;/word&gt;
        ///    &lt;word&gt;shoes&lt;/word&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LongTextOutputXml {
            get {
                return ResourceManager.GetString("LongTextOutputXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinderella likes shoes.
        /// </summary>
        internal static string OneSentenceInput {
            get {
                return ResourceManager.GetString("OneSentenceInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,Word 1,Word 2,Word 3,
        ///Sentence 1, Cinderella, likes, shoes
        ///.
        /// </summary>
        internal static string OneSentenceOutputCsv {
            get {
                return ResourceManager.GetString("OneSentenceOutputCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;text&gt;
        ///  &lt;sentence&gt;
        ///    &lt;word&gt;Cinderella&lt;/word&gt;
        ///    &lt;word&gt;likes&lt;/word&gt;
        ///    &lt;word&gt;shoes&lt;/word&gt;
        ///  &lt;/sentence&gt;
        ///&lt;/text&gt;.
        /// </summary>
        internal static string OneSentenceOutputXml {
            get {
                return ResourceManager.GetString("OneSentenceOutputXml", resourceCulture);
            }
        }
    }
}
